"""Flatten a package agent into one submittable file.

    uv run python tools/flatten_agent.py agents_1.0.x/v1_15_0_staged_field main_submit.py

The ladder loads a submission by path, from a working directory of its own
choosing, and unpacks an archive wherever it likes. A package agent has to
survive both: its entrypoint needs its own directory on `sys.path`, and
anything it reads at run time has to still be where it expects. Version 1.15.0
failed validation twice on exactly those two counts.

A single file has neither problem. This inlines the package modules in
dependency order and embeds the frozen baseline as a string, so nothing is
imported by name and nothing is read from disk.
"""

import argparse
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACKAGE = "agent_2"
ORDER = ("domain", "tasks", "model", "state", "baseline", "policy", "adapter")
BASELINE_NAME = "v1_14_0_central_herd.py"


def _strip_relative_imports(source):
    """Drop the intra-package imports; a single file already has every name."""
    source = re.sub(r"^from \.\w+ import .*$", "", source, flags=re.MULTILINE)
    return re.sub(r"^from \. import .*$", "", source, flags=re.MULTILINE)


def _use_embedded_baseline(source):
    """Read the frozen baseline from the embedded string, not from the disk.

    `BaselinePolicy` locates a file by walking up from `__file__` and executes
    it. In a submission there is no such file, and that is what failed the
    ladder validation twice.
    """
    source = source.replace(
        "self.path = Path(path).resolve() if path is not None else resolve_baseline_path()",
        "self.path = Path(path).resolve() if path is not None else None",
    )
    source = source.replace(
        "        source = self.path.read_text()",
        "        source = self.path.read_text() if self.path is not None else _BASELINE_SOURCE",
    )
    return source.replace('module.__file__ = str(self.path)',
                          'module.__file__ = str(self.path or "<embedded baseline>")')


def _hoist_imports(body):
    """Split a module into its standard-library imports and everything else."""
    imports, rest = [], []
    for line in body.splitlines():
        if re.match(r"^(import |from (?!\.)\w+ import )", line):
            if line not in imports:
                imports.append(line)
        else:
            rest.append(line)
    return imports, rest


def flatten(source_dir, baseline_path):
    package_root = source_dir / PACKAGE
    imports, rest = [], []
    for name in ORDER:
        body = _strip_relative_imports((package_root / f"{name}.py").read_text())
        if name == "baseline":
            body = _use_embedded_baseline(body)
        module_imports, module_rest = _hoist_imports(body)
        for line in module_imports:
            if line not in imports:
                imports.append(line)
        rest.extend(module_rest)
        rest.append("")

    parts = [
        '"""Single-file submission, generated by tools/flatten_agent.py.',
        "",
        "The ladder loads a submission by path and gives no guarantee about the",
        "working directory, so this file imports nothing by name from beside it",
        "and reads nothing from disk. Edit the package, not this file.",
        '"""',
        "",
        *imports,
        "",
        "",
        "_BASELINE_SOURCE = " + repr(baseline_path.read_text()),
        "",
        "",
        *rest,
        "",
        "_policy_agent = create_agent()",
        "",
        "",
        "def agent(obs):",
        "    return _policy_agent(obs)",
        "",
    ]
    return "\n".join(parts)


def _find_baseline(source_dir, override):
    if override:
        return pathlib.Path(override)
    for candidate in (source_dir / "frozen" / BASELINE_NAME,
                      ROOT / "agents_1.0.x" / BASELINE_NAME):
        if candidate.is_file():
            return candidate
    return None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="package agent directory")
    parser.add_argument("output", help="single file to write")
    parser.add_argument("--baseline", default=None, help="frozen baseline to embed")
    args = parser.parse_args()

    source_dir = pathlib.Path(args.source)
    if not source_dir.is_absolute():
        source_dir = ROOT / source_dir
    baseline = _find_baseline(source_dir, args.baseline)
    if baseline is None or not baseline.is_file():
        raise SystemExit("no frozen baseline found to embed")

    output = pathlib.Path(args.output)
    if not output.is_absolute():
        output = ROOT / output
    output.write_text(flatten(source_dir, baseline))
    print(f"{output} written, {len(output.read_text().splitlines())} lines")


if __name__ == "__main__":
    main()
